In [2]:
import pandas as pd

In [1]:
import os
from pathlib import Path

base = Path("/Users/emmamurphy/dataProjects/migranted/Data/Original data and Cleaning")
os.chdir(base)

print("Current folder:", os.getcwd())
print("Files available:")
for p in sorted(base.glob("*.csv")):
    print(" -", p.name)

Current folder: /Users/emmamurphy/dataProjects/migranted/Data/Original data and Cleaning
Files available:
 - 2023-24_ELL_Enrollment.csv
 - 2023-24_ELL_Enrollment_rural_only.csv
 - 2023-24_ELL_Enrollment_with_ZIP.csv
 - 2023-24_ELL_Enrollment_with_county.csv
 - 2023-24_ELL_Enrollment_with_county_rural_only.csv
 - 2023-24_ELL_Graduation_Rate.csv
 - 2023-24_ELL_Graduation_Rate_rural_only.csv
 - 2023-24_ELL_Graduation_Rate_with_county.csv
 - 2023-24_ELL_Graduation_Rate_with_county_rural_only.csv
 - 2023-24_ELL_Home_Languages.csv
 - 2023-24_ELL_Home_Languages_rural_only.csv
 - 2023-24_ELL_Home_Languages_with_county.csv
 - NYS_SCHOOLS.csv
 - NYS_SCHOOLS_rural_ENTITY_NAME.csv
 - UrbanInfluencecodes2024.csv
 - ell_enrollment_by_school.csv
 - ell_school_ID.csv
 - ell_school_ID_with_county.csv
 - ell_school_ID_with_county_rural_only.csv
 - ell_table.csv
 - filtered_ell_table.csv
 - rural_counties.csv

In [2]:
import pandas as pd
df = pd.read_csv("2023-24_ELL_Enrollment.csv")

In [2]:
import pandas as pd  # <-- this fixes your error

# Load the dataset
df = pd.read_csv("2023-24_ELL_Enrollment.csv")

# Select only the relevant columns
table = df[["ENTITY_NAME", "NUM_TOTAL_ELL"]]

# Drop rows with missing values
table = table.dropna()

# Aggregate totals if needed
table = table.groupby("ENTITY_NAME", as_index=False)["NUM_TOTAL_ELL"].sum()

# View the result
print(table)

# Save to a new CSV file
table.to_csv("ell_enrollment_by_school.csv", index=False)

# Display in notebook
table

                               ENTITY_NAME  NUM_TOTAL_ELL
0       ACADEMIC LEADERSHIP CHARTER SCHOOL             47
1                   ACADEMY CHARTER SCHOOL            458
2                 ACADEMY CHARTER SCHOOL 2             17
3         ACADEMY CHARTER SCHOOL-UNIONDALE            136
4            ACADEMY OF HEALTH SCIENCES CS             13
...                                    ...            ...
1045         YOUNG WOMEN'S COLLEGE PREP CS             16
1046     ZETA CHARTER - BRONX TREMONT PARK             37
1047          ZETA CHARTER SCHOOL - INWOOD             67
1048  ZETA CHARTER SCHOOL-BRONX MOUNT EDEN             90
1049       ZETA CHARTER SCHOOL-SOUTH BRONX             71

[1050 rows x 2 columns]

                               ENTITY_NAME  NUM_TOTAL_ELL
0       ACADEMIC LEADERSHIP CHARTER SCHOOL             47
1                   ACADEMY CHARTER SCHOOL            458
2                 ACADEMY CHARTER SCHOOL 2             17
3         ACADEMY CHARTER SCHOOL-UNIONDALE            136
4            ACADEMY OF HEALTH SCIENCES CS             13
...                                    ...            ...
1045         YOUNG WOMEN'S COLLEGE PREP CS             16
1046     ZETA CHARTER - BRONX TREMONT PARK             37
1047          ZETA CHARTER SCHOOL - INWOOD             67
1048  ZETA CHARTER SCHOOL-BRONX MOUNT EDEN             90
1049       ZETA CHARTER SCHOOL-SOUTH BRONX             71

[1050 rows x 2 columns]

In [3]:
import pandas as pd

In [4]:


# Load your dataset
df = pd.read_csv("2023-24_ELL_Enrollment.csv", low_memory=False)

# Select only the needed columns
table = df[["ENTITY_NAME", "INSTITUTION_ID", "NUM_TOTAL_ELL"]]

# Optional: drop rows with missing values
table = table.dropna(subset=["ENTITY_NAME", "INSTITUTION_ID", "NUM_TOTAL_ELL"])

# View result
print(table.head())

# Save to new file
table.to_csv("filtered_ell_table.csv", index=False)

                       ENTITY_NAME  INSTITUTION_ID  NUM_TOTAL_ELL
0                   ALBANY CITY SD    800000055729           1239
1          BRIGHTER CHOICE CS-BOYS    800000055520             18
2         BRIGHTER CHOICE CS-GIRLS    800000055503             33
3  KIPP TECH VALLEY CHARTER SCHOOL    800000057554             23
4     HENRY JOHNSON CHARTER SCHOOL    800000059286             18

In [5]:
from IPython.display import display

pd.set_option("display.max_rows", None)
display(table)

                               ENTITY_NAME  INSTITUTION_ID  NUM_TOTAL_ELL
0                           ALBANY CITY SD    800000055729           1239
1                  BRIGHTER CHOICE CS-BOYS    800000055520             18
2                 BRIGHTER CHOICE CS-GIRLS    800000055503             33
3          KIPP TECH VALLEY CHARTER SCHOOL    800000057554             23
4             HENRY JOHNSON CHARTER SCHOOL    800000059286             18
5                 KIPP ALBANY COMMUNITY CS    800000059310             19
6           GREEN TECH HIGH CHARTER SCHOOL    800000059776              0
7               ALBANY LEADERSHIP CS-GIRLS    800000068133             41
8                  BERNE-KNOX-WESTERLO CSD    800000055478              0
9                            BETHLEHEM CSD    800000055452             74
10             RAVENA-COEYMANS-SELKIRK CSD    800000055435             20
11                          COHOES CITY SD    800000055422             73
12                       SOUTH COLONIE CSD    800000055401            295
13                            MENANDS UFSD    800000055344             27
14                       NORTH COLONIE CSD    800000061851            388
15                       GREEN ISLAND UFSD    800000055319             22
16                         GUILDERLAND CSD    800000055306            241
17                       VOORHEESVILLE CSD    800000055278             10
18                      WATERVLIET CITY SD    800000055260            147
19                       ALFRED-ALMOND CSD    800000055275              1
20                             ANDOVER CSD    800000055223              1
21                      GENESEE VALLEY CSD    800000055232              0
22                             BELFAST CSD    800000055215              0
23                          CANASERAGA CSD    800000055188              0
24                          FRIENDSHIP CSD    800000055179              0
25                            FILLMORE CSD    800000055167              1
26                         WHITESVILLE CSD    800000055156              3
27                       CUBA-RUSHFORD CSD    800000055145              1
28                                SCIO CSD    800000055799              0
29                          WELLSVILLE CSD    800000055800              4
30                    BOLIVAR-RICHBURG CSD    800000055126              0
31                      CHENANGO FORKS CSD    800000055102             11
32                      BINGHAMTON CITY SD    800000055103            224
33                        HARPURSVILLE CSD    800000054991              1
34                  SUSQUEHANNA VALLEY CSD    800000055000              6
35                     CHENANGO VALLEY CSD    800000054967             20
36                       MAINE-ENDWELL CSD    800000054962             41
37                             DEPOSIT CSD    800000054954              6
38                       WHITNEY POINT CSD    800000054925              3
39                      UNION-ENDICOTT CSD    800000054912            114
40                        JOHNSON CITY CSD    800000054903            169
41                              VESTAL CSD    800000054880            118
42                             WINDSOR CSD    800000054848             13
43                         WEST VALLEY CSD    800000054835              0
44                  ALLEGANY-LIMESTONE CSD    800000054808              2
45                       ELLICOTTVILLE CSD    800000054788              0
46                       FRANKLINVILLE CSD    800000054780              0
47                            HINSDALE CSD    800000054770              0
48           CATTARAUGUS-LITTLE VALLEY CSD    800000054755              0
49                           OLEAN CITY SD    800000054734              7
50                             GOWANDA CSD    800000054679              0
51                           PORTVILLE CSD    800000054689              0
52                            RANDOLPH CSD    800000054668              0
53                      RANDOLPH ACAD UFSD    800000054654              2
54                       SALAMANCA CITY SD    800000054637              0
55                   YORKSHIRE-PIONEER CSD    800000054634              7
56                          AUBURN CITY SD    800000054614             42
57                           WEEDSPORT CSD    800000054541              3
58                       CATO-MERIDIAN CSD    800000054544              2
59                     SOUTHERN CAYUGA CSD    800000054518             50
60                          PORT BYRON CSD    800000054525              0
61                             MORAVIA CSD    800000054473              7
62                       UNION SPRINGS CSD    800000054503             24
63           SOUTHWESTERN CSD AT JAMESTOWN    800000054457             13
64                           FREWSBURG CSD    800000054468              0
65                    CASSADAGA VALLEY CSD    800000054436              3
66                     CHAUTAUQUA LAKE CSD    800000054415              0
67          PINE VALLEY CSD (SOUTH DAYTON)    800000054382              4
68                              CLYMER CSD    800000054363              1
69                         DUNKIRK CITY SD    800000054353            360
70                         BEMUS POINT CSD    800000054314              1
71                            FALCONER CSD    800000054292              0
72                        SILVER CREEK CSD    800000054301              4
73                         FORESTVILLE CSD    800000054269              2
74                              PANAMA CSD    800000054276              4
75                       JAMESTOWN CITY SD    800000054265            166
76                            FREDONIA CSD    800000054175             39
77                             BROCTON CSD    800000054155              7
78                              RIPLEY CSD    800000054162              3
79                             SHERMAN CSD    800000054166              2
80                           WESTFIELD CSD    800000054139              9
81                          ELMIRA CITY SD    800000054148             27
82              FINN ACADEMY: AN ELMIRA CS    800000083988              2
83                          HORSEHEADS CSD    800000054075             27
84                      ELMIRA HEIGHTS CSD    800000054045              0
85                               AFTON CSD    800000054009              1
86                 BAINBRIDGE-GUILFORD CSD    800000054036              0
87                              GREENE CSD    800000054027              9
88                     UNADILLA VALLEY CSD    800000054000              2
89                         NORWICH CITY SD    800000053997              8
90                      OTSELIC VALLEY CSD    800000053951              5
91                    OXFORD ACADEMY & CSD    800000053958              2
92                 SHERBURNE-EARLVILLE CSD    800000053941              1
93                      AUSABLE VALLEY CSD    800000053921              1
94                         BEEKMANTOWN CSD    800000053899             16
95                NORTHEASTERN CLINTON CSD    800000053886              2
96                              CHAZY UFSD    800000053881              1
97                 NORTHERN ADIRONDACK CSD    800000053866              0
98                                PERU CSD    800000053872              6
99                     PLATTSBURGH CITY SD    800000053831             40
100                            SARANAC CSD    800000053798              0
101                      TACONIC HILLS CSD    800000053780             48
102                         GERMANTOWN CSD    800000053763              7
103                            CHATHAM CSD    800000053737             25
104                         HUDSON CITY SD    800000053704            148
105                         KINDERHOOK CSD    800000053697             96
106                        NEW LEBANON CSD    800000053693              6
107                        CINCINNATUS CSD    800000053673              2
108                       CORTLAND CITY SD    800000053659             19
109                             MCGRAW CSD    800000053619              3
110                              HOMER CSD    800000053600             20
111         TRUXTON ACADEMY CHARTER SCHOOL    800000090803              2
112                           MARATHON CSD    800000053590              3
113                              ANDES CSD    800000053602              0
114                         DOWNSVILLE CSD    800000053588              0
115                   CHARLOTTE VALLEY CSD    800000053582              0
116          DELAWARE ACADEMY CSD AT DELHI    800000053586              3
117                           FRANKLIN CSD    800000053565              1
118                            HANCOCK CSD    800000053550              0
119                      MARGARETVILLE CSD    800000053535             21
120   ACHIEVEMENT FIRST LINDEN CHARTER SCH    800000082611             17
121                CYPRESS HILLS ASCEND CS    800000089574             88
122                EAST BROOKLYN ASCEND CS    800000089575             27
123           NYC GEOG DIST #20 - BROOKLYN    800000044422           9970
124           NYC GEOG DIST #21 - BROOKLYN    800000044121           7074
125            CONEY ISLAND PREP PUBLIC CS    800000063971            145
126       SUCCESS ACADEMY CS - BENSONHURST    800000082605            196
127           HEBREW LANGUAGE ACADEMY CS 2    800000089045            101
128           NYC GEOG DIST #22 - BROOKLYN    800000043961           4605
129             HEBREW LANGUAGE ACADEMY CS    800000064234            123
130         BROOKLYN DREAMS CHARTER SCHOOL    800000068331             83
131         URBAN DOVE TEAM CHARTER SCHOOL    800000070188             13
132        CENTRAL BROOKLYN ASCEND CHARTER    800000076143             69
133     NEW VISIONS CHTR HS-HUMANITIES III    800000075845              0
134     NEW VISIONS CHTR HS-ADV MA/SCI III    800000075843             19
135      SUCCESS ACADEMY CS - BERGEN BEACH    800000082606             35
136           NYC GEOG DIST #23 - BROOKLYN    800000043733            728
137       ACHIEVEMENT FIRST BROWNSVILLE CS    800000061077             62
138               OCEAN HILL COLLEGIATE CS    800000063977             24
139              BROWNSVILLE COLLEGIATE CS    800000063979              5
140          LEADERSHIP PREP OCEAN HILL CS    800000063980             43
141         LEADERSHIP PREP BROWNSVILLE CS    800000063981             24
142      BROWNSVILLE ASCEND CHARTER SCHOOL    800000064233             11
143           NYC GEOG DIST #32 - BROOKLYN    800000043653           2747
144          ACHIEVEMENT FIRST BUSHWICK CS    800000059570            222
145         BUSHWICK ASCEND CHARTER SCHOOL    800000067493            196
146   ACHIEVEMENT FIRST NORTH BROOKLYN PRE    800000076142            224
147       MESA ACADEMY CHARTER HIGH SCHOOL    800000076137             82
148            SUCCESS ACADEMY CS-BUSHWICK    800000084535            176
149             NYC GEOG DIST #24 - QUEENS    800000043407          13945
150              CENTRAL QUEENS ACADEMY CS    800000071161            147
151     MIDDLE VILLAGE PREP CHARTER SCHOOL    800000076138             25
152           FORTE PREPARATORY ACADEMY CS    800000088152             64
153           RENAISSANCE CHARTER SCHOOL 2    800000089571            197
154           ELM COMMUNITY CHARTER SCHOOL    800000089576            123
155            OUR WORLD NEIGHBORHOOD CS 3    800000090800            118
156             NYC GEOG DIST #25 - QUEENS    800000043248           7688
157             NYC GEOG DIST #26 - QUEENS    800000043080           2974
158             NYC GEOG DIST #27 - QUEENS    800000042958           5385
159              PENINSULA PREP ACADEMY CS    800000057613             54
160   CHALLENGE PREPARATORY CHARTER SCHOOL    800000067496             74
161   NEW VISIONS CHARTER HS-HUMANITIES IV    800000075844             13
162                    EAST BLOOMFIELD CSD    800000033939              9
163                         GENEVA CITY SD    800000040585            182
164   GORHAM-MIDDLESEX CSD (MARCUS WHITMAN    800000033927              1
165   MANCHESTER-SHORTSVILLE CSD (RED JACK    800000033952              5
166                             NAPLES CSD    800000033956              0
167             PHELPS-CLIFTON SPRINGS CSD    800000040538             33
168                            HONEOYE CSD    800000033947              1
169                             VICTOR CSD    800000040525             91
170                    WASHINGTONVILLE CSD    800000040518            174
171                           CHESTER UFSD    800000040500             44
172                           CORNWALL CSD    800000040474             73
173                          PINE BUSH CSD    800000040463            119
174                             GOSHEN CSD    800000040440             98
175                     HIGHLAND FALLS CSD    800000033963             68
176                     MIDDLETOWN CITY SD    800000040414           1065
177                    MINISINK VALLEY CSD    800000040344             85
178                    MONROE-WOODBURY CSD    800000040341            668
179               KIRYAS JOEL VILLAGE UFSD    800000040287            149
180                VALLEY CSD (MONTGOMERY)    800000040264             70
181                       NEWBURGH CITY SD    800000040250           1910
182                    PORT JERVIS CITY SD    800000040191             53
183                            TUXEDO UFSD    800000040171             15
184                     WARWICK VALLEY CSD    800000040158             43
185                    GREENWOOD LAKE UFSD    800000040140              7
186                           FLORIDA UFSD    800000040145             35
187                             ALBION CSD    800000050704             49
188                            KENDALL CSD    800000050758              3
189                             HOLLEY CSD    800000050761              3
190                             MEDINA CSD    800000050771              7
191                        LYNDONVILLE CSD    800000050779              7
192         ALTMAR-PARISH-WILLIAMSTOWN CSD    800000055804              0
193                         FULTON CITY SD    800000040062             52
194                           HANNIBAL CSD    800000040037              6
195                     CENTRAL SQUARE CSD    800000040024             12
196                             MEXICO CSD    800000040003              6
197                         OSWEGO CITY SD    800000039981             34
198                            ROXBURY CSD    800000053510              1
199                             SIDNEY CSD    800000053527             11
200                           STAMFORD CSD    800000053491              1
201                    SOUTH KORTRIGHT CSD    800000053489              0
202                             WALTON CSD    800000053499              5
203                         BEACON CITY SD    800000053483             49
204                             DOVER UFSD    800000053450            138
205                          HYDE PARK CSD    800000053443            159
206                          NORTHEAST CSD    800000053413            141
207                            PAWLING CSD    800000053390             77
208                        PINE PLAINS CSD    800000053377             27
209                   POUGHKEEPSIE CITY SD    800000053351            594
210            LITTLE WATER PREPARATORY CS    800000092319             19
211                          ARLINGTON CSD    800000053261            225
212                       SPACKENKILL UFSD    800000053252             35
213                           RED HOOK CSD    800000053235             61
214                          RHINEBECK CSD    800000053216             26
215                         WAPPINGERS CSD    800000053180            308
216                          MILLBROOK CSD    800000053121             21
217                              ALDEN CSD    800000053113              5
218                            AMHERST CSD    800000053090            131
219                      WILLIAMSVILLE CSD    800000053047            446
220                         SWEET HOME CSD    800000052994            217
221                       EAST AURORA UFSD    800000052988              7
222                        BUFFALO CITY SD    800000052968           5133
223             KING CENTER CHARTER SCHOOL    800000052431             21
224           SOUTH BUFFALO CHARTER SCHOOL    800000034163             10
225                TAPESTRY CHARTER SCHOOL    800000052433             22
226          BUFFALO UNITED CHARTER SCHOOL    800000056182             25
227              ENTERPRISE CHARTER SCHOOL    800000056594             20
228          BUFFALO ACADEMY OF SCIENCE CS    800000057454             92
229     WESTERN NY MARITIME CHARTER SCHOOL    800000057456             44
230               WESTMINSTER COMMUNITY CS    800000057945             48
231           ELMWOOD VILLAGE CS DAYS PARK    800000059315              6
232         HEALTH SCIENCES CHARTER SCHOOL    800000065871              9
233            WEST BUFFALO CHARTER SCHOOL    800000067492             78
234              CHARTER SCHOOL OF INQUIRY    800000083428             20
235              ELMWOOD VILLAGE CS HERTEL    800000087931             19
236           REACH ACADEMY CHARTER SCHOOL    800000087935             35
237               BUFFALO CREEK ACADEMY CS    800000091531              3
238                        PRIMARY HALL CS    800000091547              3
239       BUFFALO ACADEMY OF SCIENCE CS II    800000091548            113
240   BRICK BUFFALO ACADEMY CHARTER SCHOOL    800000092865              4
241                        CHEEKTOWAGA CSD    800000052339            262
242              CHEEKTOWAGA-MARYVALE UFSD    800000052326            292
243                    CLEVELAND HILL UFSD    800000052312             57
244                             DEPEW UFSD    800000052318             49
245                 CHEEKTOWAGA-SLOAN UFSD    800000052297             44
246                           CLARENCE CSD    800000052276             40
247          SPRINGVILLE-GRIFFITH INST CSD    800000052287              4
248                               EDEN CSD    800000052269              1
249                           IROQUOIS CSD    800000052255              4
250           EVANS-BRANT CSD (LAKE SHORE)    800000052251              5
251                       GRAND ISLAND CSD    800000052222             45
252                            HAMBURG CSD    800000052195              5
253                           FRONTIER CSD    800000052176             33
254                            HOLLAND CSD    800000052163              2
255                     LACKAWANNA CITY SD    800000052156            252
256         GLOBAL CONCEPTS CHARTER SCHOOL    800000052086            102
257                          LANCASTER CSD    800000052089             56
258                              AKRON CSD    800000052061              0
259                      NORTH COLLINS CSD    800000052056             11
260                       ORCHARD PARK CSD    800000052045             34
261                      TONAWANDA CITY SD    800000052051             40
262                 KENMORE-TONAWANDA UFSD    800000051994            214
263    CHARTER SCHOOL-APPLIED TECHNOLOGIES    800000051942            141
264                        WEST SENECA CSD    800000051957             68
265                        CROWN POINT CSD    800000051904              0
266                              KEENE CSD    800000051883              0
267                            MINERVA CSD    800000051887              0
268                             MORIAH CSD    800000051871              2

In [7]:
print(table.to_string(index=False))

                         ENTITY_NAME  INSTITUTION_ID  NUM_TOTAL_ELL
                      ALBANY CITY SD    800000055729           1239
             BRIGHTER CHOICE CS-BOYS    800000055520             18
            BRIGHTER CHOICE CS-GIRLS    800000055503             33
     KIPP TECH VALLEY CHARTER SCHOOL    800000057554             23
        HENRY JOHNSON CHARTER SCHOOL    800000059286             18
            KIPP ALBANY COMMUNITY CS    800000059310             19
      GREEN TECH HIGH CHARTER SCHOOL    800000059776              0
          ALBANY LEADERSHIP CS-GIRLS    800000068133             41
             BERNE-KNOX-WESTERLO CSD    800000055478              0
                       BETHLEHEM CSD    800000055452             74
         RAVENA-COEYMANS-SELKIRK CSD    800000055435             20
                      COHOES CITY SD    800000055422             73
                   SOUTH COLONIE CSD    800000055401            295
                        MENANDS UFSD    800000055344             27
                   NORTH COLONIE CSD    800000061851            388
                   GREEN ISLAND UFSD    800000055319             22
                     GUILDERLAND CSD    800000055306            241
                   VOORHEESVILLE CSD    800000055278             10
                  WATERVLIET CITY SD    800000055260            147
                   ALFRED-ALMOND CSD    800000055275              1
                         ANDOVER CSD    800000055223              1
                  GENESEE VALLEY CSD    800000055232              0
                         BELFAST CSD    800000055215              0
                      CANASERAGA CSD    800000055188              0
                      FRIENDSHIP CSD    800000055179              0
                        FILLMORE CSD    800000055167              1
                     WHITESVILLE CSD    800000055156              3
                   CUBA-RUSHFORD CSD    800000055145              1
                            SCIO CSD    800000055799              0
                      WELLSVILLE CSD    800000055800              4
                BOLIVAR-RICHBURG CSD    800000055126              0
                  CHENANGO FORKS CSD    800000055102             11
                  BINGHAMTON CITY SD    800000055103            224
                    HARPURSVILLE CSD    800000054991              1
              SUSQUEHANNA VALLEY CSD    800000055000              6
                 CHENANGO VALLEY CSD    800000054967             20
                   MAINE-ENDWELL CSD    800000054962             41
                         DEPOSIT CSD    800000054954              6
                   WHITNEY POINT CSD    800000054925              3
                  UNION-ENDICOTT CSD    800000054912            114
                    JOHNSON CITY CSD    800000054903            169
                          VESTAL CSD    800000054880            118
                         WINDSOR CSD    800000054848             13
                     WEST VALLEY CSD    800000054835              0
              ALLEGANY-LIMESTONE CSD    800000054808              2
                   ELLICOTTVILLE CSD    800000054788              0
                   FRANKLINVILLE CSD    800000054780              0
                        HINSDALE CSD    800000054770              0
       CATTARAUGUS-LITTLE VALLEY CSD    800000054755              0
                       OLEAN CITY SD    800000054734              7
                         GOWANDA CSD    800000054679              0
                       PORTVILLE CSD    800000054689              0
                        RANDOLPH CSD    800000054668              0
                  RANDOLPH ACAD UFSD    800000054654              2
                   SALAMANCA CITY SD    800000054637              0
               YORKSHIRE-PIONEER CSD    800000054634              7
                      AUBURN CITY SD    800000054614             42
                       WEEDSPORT CSD    800000054541              3
                   CATO-MERIDIAN CSD    800000054544              2
                 SOUTHERN CAYUGA CSD    800000054518             50
                      PORT BYRON CSD    800000054525              0
                         MORAVIA CSD    800000054473              7
                   UNION SPRINGS CSD    800000054503             24
       SOUTHWESTERN CSD AT JAMESTOWN    800000054457             13
                       FREWSBURG CSD    800000054468              0
                CASSADAGA VALLEY CSD    800000054436              3
                 CHAUTAUQUA LAKE CSD    800000054415              0
      PINE VALLEY CSD (SOUTH DAYTON)    800000054382              4
                          CLYMER CSD    800000054363              1
                     DUNKIRK CITY SD    800000054353            360
                     BEMUS POINT CSD    800000054314              1
                        FALCONER CSD    800000054292              0
                    SILVER CREEK CSD    800000054301              4
                     FORESTVILLE CSD    800000054269              2
                          PANAMA CSD    800000054276              4
                   JAMESTOWN CITY SD    800000054265            166
                        FREDONIA CSD    800000054175             39
                         BROCTON CSD    800000054155              7
                          RIPLEY CSD    800000054162              3
                         SHERMAN CSD    800000054166              2
                       WESTFIELD CSD    800000054139              9
                      ELMIRA CITY SD    800000054148             27
          FINN ACADEMY: AN ELMIRA CS    800000083988              2
                      HORSEHEADS CSD    800000054075             27
                  ELMIRA HEIGHTS CSD    800000054045              0
                           AFTON CSD    800000054009              1
             BAINBRIDGE-GUILFORD CSD    800000054036              0
                          GREENE CSD    800000054027              9
                 UNADILLA VALLEY CSD    800000054000              2
                     NORWICH CITY SD    800000053997              8
                  OTSELIC VALLEY CSD    800000053951              5
                OXFORD ACADEMY & CSD    800000053958              2
             SHERBURNE-EARLVILLE CSD    800000053941              1
                  AUSABLE VALLEY CSD    800000053921              1
                     BEEKMANTOWN CSD    800000053899             16
            NORTHEASTERN CLINTON CSD    800000053886              2
                          CHAZY UFSD    800000053881              1
             NORTHERN ADIRONDACK CSD    800000053866              0
                            PERU CSD    800000053872              6
                 PLATTSBURGH CITY SD    800000053831             40
                         SARANAC CSD    800000053798              0
                   TACONIC HILLS CSD    800000053780             48
                      GERMANTOWN CSD    800000053763              7
                         CHATHAM CSD    800000053737             25
                      HUDSON CITY SD    800000053704            148
                      KINDERHOOK CSD    800000053697             96
                     NEW LEBANON CSD    800000053693              6
                     CINCINNATUS CSD    800000053673              2
                    CORTLAND CITY SD    800000053659             19
                          MCGRAW CSD    800000053619              3
                           HOMER CSD    800000053600             20
      TRUXTON ACADEMY CHARTER SCHOOL    800000090803              2
                        MARATHON CSD    800000053590              3
                           ANDES CSD    800000053602              0
                      DOWNSVILLE CSD    800000053588              0
                CHARLOTTE VALLEY CSD    800000053582              0
       DELAWARE ACADEMY CSD AT DELHI    800000053586              3
                        FRANKLIN CSD    800000053565              1
                         HANCOCK CSD    800000053550              0
                   MARGARETVILLE CSD    800000053535             21
ACHIEVEMENT FIRST LINDEN CHARTER SCH    800000082611             17
             CYPRESS HILLS ASCEND CS    800000089574             88
             EAST BROOKLYN ASCEND CS    800000089575             27
        NYC GEOG DIST #20 - BROOKLYN    800000044422           9970
        NYC GEOG DIST #21 - BROOKLYN    800000044121           7074
         CONEY ISLAND PREP PUBLIC CS    800000063971            145
    SUCCESS ACADEMY CS - BENSONHURST    800000082605            196
        HEBREW LANGUAGE ACADEMY CS 2    800000089045            101
        NYC GEOG DIST #22 - BROOKLYN    800000043961           4605
          HEBREW LANGUAGE ACADEMY CS    800000064234            123
      BROOKLYN DREAMS CHARTER SCHOOL    800000068331             83
      URBAN DOVE TEAM CHARTER SCHOOL    800000070188             13
     CENTRAL BROOKLYN ASCEND CHARTER    800000076143             69
  NEW VISIONS CHTR HS-HUMANITIES III    800000075845              0
  NEW VISIONS CHTR HS-ADV MA/SCI III    800000075843             19
   SUCCESS ACADEMY CS - BERGEN BEACH    800000082606             35
        NYC GEOG DIST #23 - BROOKLYN    800000043733            728
    ACHIEVEMENT FIRST BROWNSVILLE CS    800000061077             62
            OCEAN HILL COLLEGIATE CS    800000063977             24
           BROWNSVILLE COLLEGIATE CS    800000063979              5
       LEADERSHIP PREP OCEAN HILL CS    800000063980             43
      LEADERSHIP PREP BROWNSVILLE CS    800000063981             24
   BROWNSVILLE ASCEND CHARTER SCHOOL    800000064233             11
        NYC GEOG DIST #32 - BROOKLYN    800000043653           2747
       ACHIEVEMENT FIRST BUSHWICK CS    800000059570            222
      BUSHWICK ASCEND CHARTER SCHOOL    800000067493            196
ACHIEVEMENT FIRST NORTH BROOKLYN PRE    800000076142            224
    MESA ACADEMY CHARTER HIGH SCHOOL    800000076137             82
         SUCCESS ACADEMY CS-BUSHWICK    800000084535            176
          NYC GEOG DIST #24 - QUEENS    800000043407          13945
           CENTRAL QUEENS ACADEMY CS    800000071161            147
  MIDDLE VILLAGE PREP CHARTER SCHOOL    800000076138             25
        FORTE PREPARATORY ACADEMY CS    800000088152             64
        RENAISSANCE CHARTER SCHOOL 2    800000089571            197
        ELM COMMUNITY CHARTER SCHOOL    800000089576            123
         OUR WORLD NEIGHBORHOOD CS 3    800000090800            118
          NYC GEOG DIST #25 - QUEENS    800000043248           7688
          NYC GEOG DIST #26 - QUEENS    800000043080           2974
          NYC GEOG DIST #27 - QUEENS    800000042958           5385
           PENINSULA PREP ACADEMY CS    800000057613             54
CHALLENGE PREPARATORY CHARTER SCHOOL    800000067496             74
NEW VISIONS CHARTER HS-HUMANITIES IV    800000075844             13
                 EAST BLOOMFIELD CSD    800000033939              9
                      GENEVA CITY SD    800000040585            182
GORHAM-MIDDLESEX CSD (MARCUS WHITMAN    800000033927              1
MANCHESTER-SHORTSVILLE CSD (RED JACK    800000033952              5
                          NAPLES CSD    800000033956              0
          PHELPS-CLIFTON SPRINGS CSD    800000040538             33
                         HONEOYE CSD    800000033947              1
                          VICTOR CSD    800000040525             91
                 WASHINGTONVILLE CSD    800000040518            174
                        CHESTER UFSD    800000040500             44
                        CORNWALL CSD    800000040474             73
                       PINE BUSH CSD    800000040463            119
                          GOSHEN CSD    800000040440             98
                  HIGHLAND FALLS CSD    800000033963             68
                  MIDDLETOWN CITY SD    800000040414           1065
                 MINISINK VALLEY CSD    800000040344             85
                 MONROE-WOODBURY CSD    800000040341            668
            KIRYAS JOEL VILLAGE UFSD    800000040287            149
             VALLEY CSD (MONTGOMERY)    800000040264             70
                    NEWBURGH CITY SD    800000040250           1910
                 PORT JERVIS CITY SD    800000040191             53
                         TUXEDO UFSD    800000040171             15
                  WARWICK VALLEY CSD    800000040158             43
                 GREENWOOD LAKE UFSD    800000040140              7
                        FLORIDA UFSD    800000040145             35
                          ALBION CSD    800000050704             49
                         KENDALL CSD    800000050758              3
                          HOLLEY CSD    800000050761              3
                          MEDINA CSD    800000050771              7
                     LYNDONVILLE CSD    800000050779              7
      ALTMAR-PARISH-WILLIAMSTOWN CSD    800000055804              0
                      FULTON CITY SD    800000040062             52
                        HANNIBAL CSD    800000040037              6
                  CENTRAL SQUARE CSD    800000040024             12
                          MEXICO CSD    800000040003              6
                      OSWEGO CITY SD    800000039981             34
                         ROXBURY CSD    800000053510              1
                          SIDNEY CSD    800000053527             11
                        STAMFORD CSD    800000053491              1
                 SOUTH KORTRIGHT CSD    800000053489              0
                          WALTON CSD    800000053499              5
                      BEACON CITY SD    800000053483             49
                          DOVER UFSD    800000053450            138
                       HYDE PARK CSD    800000053443            159
                       NORTHEAST CSD    800000053413            141
                         PAWLING CSD    800000053390             77
                     PINE PLAINS CSD    800000053377             27
                POUGHKEEPSIE CITY SD    800000053351            594
         LITTLE WATER PREPARATORY CS    800000092319             19
                       ARLINGTON CSD    800000053261            225
                    SPACKENKILL UFSD    800000053252             35
                        RED HOOK CSD    800000053235             61
                       RHINEBECK CSD    800000053216             26
                      WAPPINGERS CSD    800000053180            308
                       MILLBROOK CSD    800000053121             21
                           ALDEN CSD    800000053113              5
                         AMHERST CSD    800000053090            131
                   WILLIAMSVILLE CSD    800000053047            446
                      SWEET HOME CSD    800000052994            217
                    EAST AURORA UFSD    800000052988              7
                     BUFFALO CITY SD    800000052968           5133
          KING CENTER CHARTER SCHOOL    800000052431             21
        SOUTH BUFFALO CHARTER SCHOOL    800000034163             10
             TAPESTRY CHARTER SCHOOL    800000052433             22
       BUFFALO UNITED CHARTER SCHOOL    800000056182             25
           ENTERPRISE CHARTER SCHOOL    800000056594             20
       BUFFALO ACADEMY OF SCIENCE CS    800000057454             92
  WESTERN NY MARITIME CHARTER SCHOOL    800000057456             44
            WESTMINSTER COMMUNITY CS    800000057945             48
        ELMWOOD VILLAGE CS DAYS PARK    800000059315              6
      HEALTH SCIENCES CHARTER SCHOOL    800000065871              9
         WEST BUFFALO CHARTER SCHOOL    800000067492             78
           CHARTER SCHOOL OF INQUIRY    800000083428             20
           ELMWOOD VILLAGE CS HERTEL    800000087931             19
        REACH ACADEMY CHARTER SCHOOL    800000087935             35
            BUFFALO CREEK ACADEMY CS    800000091531              3
                     PRIMARY HALL CS    800000091547              3
    BUFFALO ACADEMY OF SCIENCE CS II    800000091548            113
BRICK BUFFALO ACADEMY CHARTER SCHOOL    800000092865              4
                     CHEEKTOWAGA CSD    800000052339            262
           CHEEKTOWAGA-MARYVALE UFSD    800000052326            292
                 CLEVELAND HILL UFSD    800000052312             57
                          DEPEW UFSD    800000052318             49
              CHEEKTOWAGA-SLOAN UFSD    800000052297             44
                        CLARENCE CSD    800000052276             40
       SPRINGVILLE-GRIFFITH INST CSD    800000052287              4
                            EDEN CSD    800000052269              1
                        IROQUOIS CSD    800000052255              4
        EVANS-BRANT CSD (LAKE SHORE)    800000052251              5
                    GRAND ISLAND CSD    800000052222             45
                         HAMBURG CSD    800000052195              5
                        FRONTIER CSD    800000052176             33
                         HOLLAND CSD    800000052163              2
                  LACKAWANNA CITY SD    800000052156            252
      GLOBAL CONCEPTS CHARTER SCHOOL    800000052086            102
                       LANCASTER CSD    800000052089             56
                           AKRON CSD    800000052061              0
                   NORTH COLLINS CSD    800000052056             11
                    ORCHARD PARK CSD    800000052045             34
                   TONAWANDA CITY SD    800000052051             40
              KENMORE-TONAWANDA UFSD    800000051994            214
 CHARTER SCHOOL-APPLIED TECHNOLOGIES    800000051942            141
                     WEST SENECA CSD    800000051957             68
                     CROWN POINT CSD    800000051904              0
                           KEENE CSD    800000051883              0
                         MINERVA CSD    800000051887              0
                          MORIAH CSD    800000051871              2
                         NEWCOMB CSD    800000051865              0
                     LAKE PLACID CSD    800000051868             10
                    SCHROON LAKE CSD    800000051839              1
                     TICONDEROGA CSD    800000051823              1
                       WILLSBORO CSD    800000051817              0
                   BOQUET VALLEY CSD    800000091298              0
                     TUPPER LAKE CSD    800000051805              1
                      CHATEAUGAY CSD    800000051798              0
                    SALMON RIVER CSD    800000051790              0
                    SARANAC LAKE CSD    800000051779              1
                          MALONE CSD    800000051755              1
                  BRUSHTON-MOIRA CSD    800000051709              0
                  ST REGIS FALLS CSD    800000051699              0
                GLOVERSVILLE CITY SD    800000051678             23
                   JOHNSTOWN CITY SD    800000051668             13
                        MAYFIELD CSD    800000051650              1
                      NORTHVILLE CSD    800000051634              0
                BROADALBIN-PERTH CSD    800000051614              5
                       ALEXANDER CSD    800000034031              5
                     BATAVIA CITY SD    800000034034             42
                    BYRON-BERGEN CSD    800000034015              6
                            ELBA CSD    800000034019             25
                          LE ROY CSD    800000033992              7
                OAKFIELD-ALABAMA CSD    800000033993              5

In [8]:
table.to_csv("ell_table.csv", index=False)

In [27]:
import pandas as pd

df = pd.read_csv("UrbanInfluencecodes2024.csv")

df.head()

,FIPS-UIC,State,County_Name,Attribute,Value
0,1001,AL,Autauga County,Population_2020,58805
1,1001,AL,Autauga County,UIC_2024,4
2,1001,AL,Autauga County,Description,Small metro (in a metro area with fewer than 1...
3,1003,AL,Baldwin County,Population_2020,231767
4,1003,AL,Baldwin County,UIC_2024,4

In [28]:
# Keep only UIC_2024 rows first
if "Attribute" not in df.columns:
    raise ValueError(f"'Attribute' column not found. Columns: {list(df.columns)}")

df = df[df["Attribute"].astype(str).str.strip().eq("UIC_2024")].copy()

df

      FIPS-UIC State        County_Name Attribute Value
1         1001    AL     Autauga County  UIC_2024     4
4         1003    AL     Baldwin County  UIC_2024     4
7         1005    AL     Barbour County  UIC_2024     5
10        1007    AL        Bibb County  UIC_2024     1
13        1009    AL      Blount County  UIC_2024     1
...        ...   ...                ...       ...   ...
9689     72151    PR  Yabucoa Municipio  UIC_2024     1
9692     72153    PR    Yauco Municipio  UIC_2024     4
9695     78010    VI   St. Croix Island  UIC_2024     9
9698     78020    VI    St. John Island  UIC_2024     9
9701     78030    VI  St. Thomas Island  UIC_2024     8

[3233 rows x 5 columns]

In [29]:
# Then keep only NY rows
if "State" not in df.columns:
    raise ValueError(f"'State' column not found. Columns: {list(df.columns)}")

df = df[df["State"].astype(str).str.strip().str.upper().eq("NY")].copy()

df

      FIPS-UIC State         County_Name Attribute Value
5491     36001    NY       Albany County  UIC_2024     4
5494     36003    NY     Allegany County  UIC_2024     9
5497     36005    NY        Bronx County  UIC_2024     1
5500     36007    NY       Broome County  UIC_2024     4
5503     36009    NY  Cattaraugus County  UIC_2024     2
...        ...   ...                 ...       ...   ...
5662     36115    NY   Washington County  UIC_2024     4
5665     36117    NY        Wayne County  UIC_2024     1
5668     36119    NY  Westchester County  UIC_2024     1
5671     36121    NY      Wyoming County  UIC_2024     3
5674     36123    NY        Yates County  UIC_2024     3

[62 rows x 5 columns]

In [30]:
import pandas as pd

# 1) Attribute filter
df = df[df["Attribute"].astype(str).str.strip().eq("UIC_2024")].copy()

# 2) NY filter
df = df[df["State"].astype(str).str.strip().str.upper().eq("NY")].copy()

# 3) Value >= 4
if "Value" not in df.columns:
    raise ValueError(f"'Value' column not found. Columns: {list(df.columns)}")

df["Value_num"] = pd.to_numeric(df["Value"], errors="coerce")
df = df[df["Value_num"] >= 4].copy()

df

      FIPS-UIC State          County_Name Attribute Value  Value_num
5491     36001    NY        Albany County  UIC_2024     4          4
5494     36003    NY      Allegany County  UIC_2024     9          9
5500     36007    NY        Broome County  UIC_2024     4          4
5506     36011    NY        Cayuga County  UIC_2024     5          5
5512     36015    NY       Chemung County  UIC_2024     4          4
5515     36017    NY      Chenango County  UIC_2024     6          6
5518     36019    NY       Clinton County  UIC_2024     5          5
5521     36021    NY      Columbia County  UIC_2024     5          5
5524     36023    NY      Cortland County  UIC_2024     5          5
5527     36025    NY      Delaware County  UIC_2024     6          6
5530     36027    NY      Dutchess County  UIC_2024     4          4
5536     36031    NY         Essex County  UIC_2024     6          6
5539     36033    NY      Franklin County  UIC_2024     8          8
5542     36035    NY        Fulton County  UIC_2024     5          5
5548     36039    NY        Greene County  UIC_2024     6          6
5551     36041    NY      Hamilton County  UIC_2024     6          6
5554     36043    NY      Herkimer County  UIC_2024     4          4
5557     36045    NY     Jefferson County  UIC_2024     4          4
5563     36049    NY         Lewis County  UIC_2024     6          6
5569     36053    NY       Madison County  UIC_2024     4          4
5575     36057    NY    Montgomery County  UIC_2024     5          5
5587     36065    NY        Oneida County  UIC_2024     4          4
5590     36067    NY      Onondaga County  UIC_2024     4          4
5596     36071    NY        Orange County  UIC_2024     4          4
5602     36075    NY        Oswego County  UIC_2024     4          4
5605     36077    NY        Otsego County  UIC_2024     7          7
5614     36083    NY    Rensselaer County  UIC_2024     4          4
5623     36089    NY  St. Lawrence County  UIC_2024     5          5
5626     36091    NY      Saratoga County  UIC_2024     4          4
5629     36093    NY   Schenectady County  UIC_2024     4          4
5632     36095    NY     Schoharie County  UIC_2024     4          4
5635     36097    NY      Schuyler County  UIC_2024     6          6
5647     36105    NY      Sullivan County  UIC_2024     5          5
5650     36107    NY         Tioga County  UIC_2024     4          4
5653     36109    NY      Tompkins County  UIC_2024     4          4
5656     36111    NY        Ulster County  UIC_2024     4          4
5659     36113    NY        Warren County  UIC_2024     4          4
5662     36115    NY    Washington County  UIC_2024     4          4

In [32]:
import pandas as pd

# Build filtered dataframe
df = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/UrbanInfluencecodes2024.csv", dtype=str)
df.columns = [c.strip() for c in df.columns]

df = df[df["Attribute"].astype(str).str.strip().eq("UIC_2024")].copy()
df = df[df["State"].astype(str).str.strip().str.upper().eq("NY")].copy()
df["Value_num"] = pd.to_numeric(df["Value"], errors="coerce")
df = df[df["Value_num"] >= 4].copy()

# Save CSV
out_file = "rural_nys_school.csv"
df.to_csv(out_file, index=False)
print(f"Saved: {out_file} ({len(df)} rows)")

Saved: rural_nys_school.csv (38 rows)

In [23]:
import pandas as pd
import re

# Input files
rural_file = "rural_nys_school.csv"   # or "rural_nys_schools_csv.csv" if that is your actual filename
schools_file = "NYS_SCHOOLS.csv"

# Output file
out_file = "NYS_SCHOOLS_rural_counties.csv"

def norm_county(x):
    if pd.isna(x):
        return ""
    s = str(x).upper().strip()
    s = s.replace("&", "AND")
    s = re.sub(r"\bST\b\.?", "SAINT", s)
    s = re.sub(r"\bCOUNTY\b", "", s)
    s = re.sub(r"[^A-Z0-9 ]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

# Load
rural = pd.read_csv(rural_file, dtype=str)
schools = pd.read_csv(schools_file, dtype=str)

# Detect county columns
rural_county_col = "County_Name" if "County_Name" in rural.columns else "COUNTY"
schools_county_col = "County_Name" if "County_Name" in schools.columns else "COUNTY"

if rural_county_col not in rural.columns:
    raise ValueError(f"County column not found in rural file. Columns: {list(rural.columns)}")
if schools_county_col not in schools.columns:
    raise ValueError(f"County column not found in schools file. Columns: {list(schools.columns)}")

# County set from rural file
rural_counties = set(rural[rural_county_col].map(norm_county).dropna())

# Filter NYS_SCHOOLS to only those counties
schools["_county_norm"] = schools[schools_county_col].map(norm_county)
filtered = schools[schools["_county_norm"].isin(rural_counties)].copy()
filtered = filtered.drop(columns=["_county_norm"])

df

     FIPS-UIC State      County_Name Attribute Value  Value_num
5494    36003    NY  Allegany County  UIC_2024     9          9
5515    36017    NY  Chenango County  UIC_2024     6          6
5527    36025    NY  Delaware County  UIC_2024     6          6
5536    36031    NY     Essex County  UIC_2024     6          6
5539    36033    NY  Franklin County  UIC_2024     8          8
5548    36039    NY    Greene County  UIC_2024     6          6
5551    36041    NY  Hamilton County  UIC_2024     6          6
5563    36049    NY     Lewis County  UIC_2024     6          6
5605    36077    NY    Otsego County  UIC_2024     7          7
5635    36097    NY  Schuyler County  UIC_2024     6          6

In [42]:
import pandas as pd

# Load Excel file
df = pd.read_excel("rural_counties.xlsx")

# Save as CSV
csv_path = "rural_counties.csv"
df.to_csv(csv_path, index=False)

print("CSV file created:", csv_path)

CSV file created: rural_counties.csv

In [43]:
from IPython.display import FileLink

FileLink("rural_counties.csv")

/Users/emmamurphy/dataProjects/migranted/Data/rural_counties.csv

In [55]:
import pandas as pd

# Load files
schools = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS.csv")
rural = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/rural_counties.csv")

# Standardize column names
schools.columns = schools.columns.str.strip()
rural.columns = rural.columns.str.strip()

# Clean matching fields
schools["COUNTY"] = schools["COUNTY"].str.strip().str.upper()
rural["County_Name"] = rural["County_Name"].str.strip().str.upper()

# Get rural county list
rural_list = rural["County_Name"].unique()

# KEEP only rural counties from schools
rural_schools = schools[schools["COUNTY"].isin(rural_list)].copy()

# Save output
output_path = "/Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS_rural.csv"
rural_schools.to_csv(output_path, index=False)

print(f"Saved {len(rural_schools)} rural school records to: {output_path}")

Saved 236 rural school records to: /Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS_rural.csv

In [56]:
import pandas as pd

# Load the rural schools file
rural_schools = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS_rural.csv")

# Drop the specified columns
columns_to_drop = ["SED CODE", "ADDR LINE 1", "ADDR LINE 2", "P", "S", "STATE"]

# Only drop columns that exist in the dataframe
columns_to_drop = [col for col in columns_to_drop if col in rural_schools.columns]

rural_schools_cleaned = rural_schools.drop(columns=columns_to_drop)

# Save output
output_path = "/Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS_rural_cleaned.csv"
rural_schools_cleaned.to_csv(output_path, index=False)

print(f"Removed columns: {columns_to_drop}")
print(f"Remaining columns: {list(rural_schools_cleaned.columns)}")
print(f"Saved to: {output_path}")

Removed columns: ['SED CODE', 'ADDR LINE 1', 'ADDR LINE 2', 'P', 'S', 'STATE']
Remaining columns: ['COUNTY', 'POPULAR NAME', 'CITY', 'ZIP', 'INSTITUTION ID']
Saved to: /Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS_rural_cleaned.csv

In [60]:
import pandas as pd

ell = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/ell_enrollment_by_school.csv")
rural = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/NYS_SCHOOLS_rural_cleaned.csv")

print("ELL columns:", ell.columns.tolist())
print("Rural columns:", rural.columns.tolist())

ELL columns: ['ENTITY_NAME', 'NUM_TOTAL_ELL']
Rural columns: ['COUNTY', 'POPULAR NAME', 'CITY', 'ZIP', 'INSTITUTION_ID']

In [4]:
#### THIS CODE COMBINES ADDS A COUNTY COLLUMN TO THE GRADUATION RATES CSV

import pandas as pd
import re
from IPython.display import display

# Paths
grad_path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate.csv"
county_ref_path = "/Users/emmamurphy/dataProjects/migranted/Data/ell_school_ID_with_county.csv"
out_path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_with_county.csv"

# Load
grad = pd.read_csv(grad_path, dtype=str)
ref = pd.read_csv(county_ref_path, dtype=str)

# Clean column names
grad.columns = grad.columns.str.strip()
ref.columns = ref.columns.str.strip()

# Ensure key columns are strings
for c in ["INSTITUTION_ID", "ENTITY_CD", "ENTITY_NAME"]:
    if c in grad.columns:
        grad[c] = grad[c].fillna("").astype(str).str.strip()
    if c in ref.columns:
        ref[c] = ref[c].fillna("").astype(str).str.strip()

# Ensure COUNTY exists in output
if "COUNTY" not in grad.columns:
    grad["COUNTY"] = ""

# ---------- 1) Match by INSTITUTION_ID ----------
id_map = (
    ref.loc[ref["INSTITUTION_ID"] != "", ["INSTITUTION_ID", "COUNTY"]]
    .dropna(subset=["COUNTY"])
    .drop_duplicates(subset=["INSTITUTION_ID"])
    .set_index("INSTITUTION_ID")["COUNTY"]
)
missing = grad["COUNTY"].eq("")
grad.loc[missing, "COUNTY"] = grad.loc[missing, "INSTITUTION_ID"].map(id_map).fillna("")

# ---------- 2) Match by ENTITY_CD ----------
cd_map = (
    ref.loc[ref["ENTITY_CD"] != "", ["ENTITY_CD", "COUNTY"]]
    .dropna(subset=["COUNTY"])
    .drop_duplicates(subset=["ENTITY_CD"])
    .set_index("ENTITY_CD")["COUNTY"]
)
missing = grad["COUNTY"].eq("")
grad.loc[missing, "COUNTY"] = grad.loc[missing, "ENTITY_CD"].map(cd_map).fillna("")

# ---------- 3) Fallback: match by normalized ENTITY_NAME ----------
def norm_name(x):
    s = "" if pd.isna(x) else str(x).upper().strip()
    s = re.sub(r"[^A-Z0-9 ]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

grad["__name_key"] = grad["ENTITY_NAME"].map(norm_name)
ref["__name_key"] = ref["ENTITY_NAME"].map(norm_name)

name_map = (
    ref.loc[ref["__name_key"] != "", ["__name_key", "COUNTY"]]
    .dropna(subset=["COUNTY"])
    .drop_duplicates(subset=["__name_key"])
    .set_index("__name_key")["COUNTY"]
)
missing = grad["COUNTY"].eq("")
grad.loc[missing, "COUNTY"] = grad.loc[missing, "__name_key"].map(name_map).fillna("")

# Cleanup temp column
grad.drop(columns=["__name_key"], inplace=True)

# Save
grad.to_csv(out_path, index=False)

# Quick check
print("Saved:", out_path)
print("Total rows:", len(grad))
print("Rows with COUNTY:", (grad["COUNTY"].str.strip() != "").sum())
print("Rows missing COUNTY:", (grad["COUNTY"].str.strip() == "").sum())

# Small excerpt
display(grad[["ENTITY_NAME", "INSTITUTION_ID", "ENTITY_CD", "COUNTY"]].head(15))

Saved: /Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_with_county.csv
Total rows: 3885
Rows with COUNTY: 3885
Rows missing COUNTY: 0

           ENTITY_NAME INSTITUTION_ID    ENTITY_CD  COUNTY
0    GREEN ISLAND UFSD   800000055319  10701030000  ALBANY
1    GREEN ISLAND UFSD   800000055319  10701030000  ALBANY
2      GUILDERLAND CSD   800000055306  10802060000  ALBANY
3      GUILDERLAND CSD   800000055306  10802060000  ALBANY
4      GUILDERLAND CSD   800000055306  10802060000  ALBANY
5      GUILDERLAND CSD   800000055306  10802060000  ALBANY
6      GUILDERLAND CSD   800000055306  10802060000  ALBANY
7    VOORHEESVILLE CSD   800000055278  11003060000  ALBANY
8    VOORHEESVILLE CSD   800000055278  11003060000  ALBANY
9    VOORHEESVILLE CSD   800000055278  11003060000  ALBANY
10   VOORHEESVILLE CSD   800000055278  11003060000  ALBANY
11   VOORHEESVILLE CSD   800000055278  11003060000  ALBANY
12  WATERVLIET CITY SD   800000055260  11200010000  ALBANY
13  WATERVLIET CITY SD   800000055260  11200010000  ALBANY
14  WATERVLIET CITY SD   800000055260  11200010000  ALBANY

In [8]:
import pandas as pd
import re
from IPython.display import display

# Paths
grad_path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_with_county.csv"
rural_path = "/Users/emmamurphy/dataProjects/migranted/Data/rural_counties.csv"
out_path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_rural_only.csv"

def norm_county(x):
    if pd.isna(x):
        return ""
    s = str(x).upper().strip()
    s = s.replace(".", "")          # ST. -> ST
    s = re.sub(r"\bCOUNTY\b", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

# Load files
grad = pd.read_csv(grad_path, dtype=str)
rural = pd.read_csv(rural_path, dtype=str)

# Clean columns
grad.columns = grad.columns.str.strip()
rural.columns = rural.columns.str.strip()

if "COUNTY" not in grad.columns:
    raise ValueError("COUNTY column not found in graduation file.")
if "County_Name" not in rural.columns:
    raise ValueError("County_Name column not found in rural_counties.csv.")

# Build allowed rural county set
allowed = set(rural["County_Name"].map(norm_county).dropna())

# Filter graduation rows to only allowed counties
grad["_county_norm"] = grad["COUNTY"].map(norm_county)
rural_only = grad[grad["_county_norm"].isin(allowed)].copy()
rural_only.drop(columns=["_county_norm"], inplace=True)

# Save
rural_only.to_csv(out_path, index=False)

# Checks
print("Allowed rural counties:", len(allowed))
print("Input rows:", len(grad))
print("Output rows:", len(rural_only))
print("Albany rows kept:", (rural_only["COUNTY"].astype(str).str.upper().str.strip() == "ALBANY").sum())
print("Saved:", out_path)

# Small excerpt
display(rural_only[["ENTITY_NAME", "INSTITUTION_ID", "ENTITY_CD", "COUNTY"]].head(15))

Allowed rural counties: 33
Input rows: 3885
Output rows: 1305
Albany rows kept: 0
Saved: /Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_rural_only.csv

           ENTITY_NAME INSTITUTION_ID    ENTITY_CD    COUNTY
65   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
66   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
67   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
68   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
69   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
70         ANDOVER CSD   800000055223  20601040000  ALLEGANY
71         ANDOVER CSD   800000055223  20601040000  ALLEGANY
72         ANDOVER CSD   800000055223  20601040000  ALLEGANY
73         ANDOVER CSD   800000055223  20601040000  ALLEGANY
74         ANDOVER CSD   800000055223  20601040000  ALLEGANY
75  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
76  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
77  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
78  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
79  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY

In [11]:
# CHECKING IF ALL 33 COUNTIES ARE INCLUDED

# Distinct counties in filtered output
included_norm = sorted(set(rural_only["COUNTY"].map(norm_county)) - {""})
included_raw = sorted(set(rural_only["COUNTY"].astype(str).str.strip()) - {""})

print("Distinct counties included (normalized):", len(included_norm))
print("Distinct counties included (raw):", len(included_raw))

# Compare to allowed rural county list
missing_from_output = sorted(set(allowed) - set(included_norm))
unexpected_in_output = sorted(set(included_norm) - set(allowed))

print("Allowed rural counties total:", len(allowed))
print("Allowed counties missing from output:", len(missing_from_output))
print("Unexpected counties in output:", len(unexpected_in_output))

print("\nIncluded counties (normalized):")
print(included_norm)

if missing_from_output:
    print("\nMissing allowed counties:")
    print(missing_from_output)

if unexpected_in_output:
    print("\nUnexpected counties:")
    print(unexpected_in_output)

# Optional: rows per county
county_counts = (
    rural_only.assign(COUNTY_NORM=rural_only["COUNTY"].map(norm_county))
             .groupby("COUNTY_NORM", dropna=False)
             .size()
             .reset_index(name="ROW_COUNT")
             .sort_values("ROW_COUNT", ascending=False)
)
display(county_counts.head(50))

Distinct counties included (normalized): 31
Distinct counties included (raw): 31
Allowed rural counties total: 33
Allowed counties missing from output: 2
Unexpected counties in output: 0

Included counties (normalized):
['ALLEGANY', 'BROOME', 'CAYUGA', 'CHEMUNG', 'CHENANGO', 'CLINTON', 'COLUMBIA', 'CORTLAND', 'DELAWARE', 'ESSEX', 'FRANKLIN', 'FULTON', 'HAMILTON', 'HERKIMER', 'JEFFERSON', 'LEWIS', 'MADISON', 'MONTGOMERY', 'ONEIDA', 'ORANGE', 'OSWEGO', 'OTSEGO', 'SCHENECTADY', 'SCHOHARIE', 'SCHUYLER', 'SULLIVAN', 'TIOGA', 'TOMPKINS', 'ULSTER', 'WARREN', 'WASHINGTON']

Missing allowed counties:
['GREENE', 'ST LAWRENCE']

    COUNTY_NORM  ROW_COUNT
8      DELAWARE         90
19       ORANGE         80
18       ONEIDA         75
0      ALLEGANY         60
21       OTSEGO         60
1        BROOME         60
13     HERKIMER         55
14    JEFFERSON         55
16      MADISON         50
30   WASHINGTON         50
9         ESSEX         50
20       OSWEGO         45
28       ULSTER         45
29       WARREN         40
27     TOMPKINS         40
5       CLINTON         40
25     SULLIVAN         40
4      CHENANGO         40
2        CAYUGA         35
10     FRANKLIN         35
22  SCHENECTADY         30
23    SCHOHARIE         30
26        TIOGA         30
6      COLUMBIA         30
11       FULTON         25
17   MONTGOMERY         25
7      CORTLAND         25
15        LEWIS         25
3       CHEMUNG         15
12     HAMILTON         15
24     SCHUYLER         10

In [12]:
# FINDING OUT WHICH TWO AREN'T INCLUDED AND WHY
missing = sorted(set(allowed) - set(included_norm))
print("Missing counties:", missing)

# Check if those counties exist anywhere in grad file before filtering
grad_check = grad.copy()
grad_check["COUNTY_NORM"] = grad_check["COUNTY"].map(norm_county)

for c in missing:
    rows_with_county = grad_check[grad_check["COUNTY_NORM"] == c]
    print(f"\n{c}: rows in grad with this COUNTY =", len(rows_with_county))
    if len(rows_with_county) == 0:
        # find possible rows by ENTITY_NAME hint
        hint = c.replace("ST ", "ST. ")
        name_hits = grad_check[
            grad_check["ENTITY_NAME"].astype(str).str.upper().str.contains(c, na=False) |
            grad_check["ENTITY_NAME"].astype(str).str
                .upper().str.contains(hint, na=False)
        ]
        print("Possible ENTITY_NAME hits with missing/other county:", len(name_hits))
        display(name_hits[["ENTITY_NAME","INSTITUTION_ID","ENTITY_CD","COUNTY"]].head(20))

Missing counties: ['GREENE', 'ST LAWRENCE']

GREENE: rows in grad with this COUNTY = 0
Possible ENTITY_NAME hits with missing/other county: 5

    ENTITY_NAME INSTITUTION_ID    ENTITY_CD    COUNTY
390  GREENE CSD   800000054027  80601040000  CHENANGO
391  GREENE CSD   800000054027  80601040000  CHENANGO
392  GREENE CSD   800000054027  80601040000  CHENANGO
393  GREENE CSD   800000054027  80601040000  CHENANGO
394  GREENE CSD   800000054027  80601040000  CHENANGO

ST LAWRENCE: rows in grad with this COUNTY = 0
Possible ENTITY_NAME hits with missing/other county: 0

Empty DataFrame
Columns: [ENTITY_NAME, INSTITUTION_ID, ENTITY_CD, COUNTY]
Index: []

In [13]:
#### CHECKING WHY THERE ARE NO ST. LAWRENCE COUNTIES

import pandas as pd

grad = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_with_county.csv", dtype=str)
ref  = pd.read_csv("/Users/emmamurphy/dataProjects/migranted/Data/ell_school_ID_with_county.csv", dtype=str)

grad.columns = grad.columns.str.strip()
ref.columns = ref.columns.str.strip()

# Build COUNTY_CODE -> COUNTY map from your reference file
code_map = (
    ref[["COUNTY_CODE", "COUNTY"]]
    .dropna()
    .drop_duplicates("COUNTY_CODE")
)
code_to_county = dict(zip(code_map["COUNTY_CODE"].str.zfill(2), code_map["COUNTY"]))

# Derive 2-digit county code from ENTITY_CD
grad["ENTITY_CD"] = grad["ENTITY_CD"].fillna("").astype(str).str.strip()
grad["CC2"] = grad["ENTITY_CD"].str.extract(r"^(\d{1,2})")[0].str.zfill(2)
grad["COUNTY_FROM_CODE"] = grad["CC2"].map(code_to_county)

# Check St. Lawrence candidates
stl = grad[grad["COUNTY_FROM_CODE"].fillna("").str.upper().str.replace(".", "", regex=False).eq("ST LAWRENCE")]
print("Rows whose ENTITY_CD maps to ST LAWRENCE:", len(stl))
display(stl[["ENTITY_NAME","INSTITUTION_ID","ENTITY_CD","COUNTY","COUNTY_FROM_CODE"]].head(20))

Rows whose ENTITY_CD maps to ST LAWRENCE: 0

Empty DataFrame
Columns: [ENTITY_NAME, INSTITUTION_ID, ENTITY_CD, COUNTY, COUNTY_FROM_CODE]
Index: []

In [14]:
#### ADDING IN ST. LAWRENCE COUNTY

import pandas as pd
import re
from IPython.display import display

grad_path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_with_county.csv"
rural_path = "/Users/emmamurphy/dataProjects/migranted/Data/rural_counties.csv"
out_path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_rural_only.csv"

def norm_county(x):
    if pd.isna(x):
        return ""
    s = str(x).upper().strip()
    s = s.replace(".", "")
    s = re.sub(r"\bCOUNTY\b", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    # treat ST and SAINT the same
    s = s.replace("ST LAWRENCE", "SAINT LAWRENCE")
    return s

# Load files
grad = pd.read_csv(grad_path, dtype=str)
rural = pd.read_csv(rural_path, dtype=str)

grad.columns = grad.columns.str.strip()
rural.columns = rural.columns.str.strip()

if "COUNTY" not in grad.columns:
    raise ValueError("COUNTY column not found in graduation file.")
if "County_Name" not in rural.columns:
    raise ValueError("County_Name column not found in rural_counties.csv.")

# Build rural county keep-list
allowed = set(rural["County_Name"].map(norm_county).dropna())

# Ensure St. Lawrence is included in the keep-list
allowed.add("SAINT LAWRENCE")

# Filter graduation file
grad["_county_norm"] = grad["COUNTY"].map(norm_county)
rural_only = grad[grad["_county_norm"].isin(allowed)].copy()
rural_only.drop(columns=["_county_norm"], inplace=True)

# Save
rural_only.to_csv(out_path, index=False)

# Checks
print("Allowed counties:", len(allowed))
print("Input rows:", len(grad))
print("Output rows:", len(rural_only))
print("St. Lawrence rows kept:", rural_only["COUNTY"].astype(str).str.upper().str.contains("ST|SAINT", na=False).sum())
print("Saved:", out_path)

display(rural_only[["ENTITY_NAME", "INSTITUTION_ID", "ENTITY_CD", "COUNTY"]].head(15))

Allowed counties: 33
Input rows: 3885
Output rows: 1390
St. Lawrence rows kept: 130
Saved: /Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_rural_only.csv

           ENTITY_NAME INSTITUTION_ID    ENTITY_CD    COUNTY
65   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
66   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
67   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
68   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
69   ALFRED-ALMOND CSD   800000055275  20101040000  ALLEGANY
70         ANDOVER CSD   800000055223  20601040000  ALLEGANY
71         ANDOVER CSD   800000055223  20601040000  ALLEGANY
72         ANDOVER CSD   800000055223  20601040000  ALLEGANY
73         ANDOVER CSD   800000055223  20601040000  ALLEGANY
74         ANDOVER CSD   800000055223  20601040000  ALLEGANY
75  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
76  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
77  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
78  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY
79  GENESEE VALLEY CSD   800000055232  20702040000  ALLEGANY

In [16]:
import pandas as pd
import re

# If you already have rural_only loaded, you can skip reloading
path = "/Users/emmamurphy/dataProjects/migranted/Data/2023-24_ELL_Graduation_Rate_rural_only.csv"
df = pd.read_csv(path, dtype=str)

def norm_county(x):
    if pd.isna(x):
        return ""
    s = str(x).upper().strip()
    s = s.replace(".", "")
    s = re.sub(r"\bCOUNTY\b", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

df["COUNTY_NORM"] = df["COUNTY"].map(norm_county)

distinct_counties = sorted(set(df["COUNTY_NORM"]) - {""})

print("Distinct counties present:", len(distinct_counties))
print(distinct_counties)

Distinct counties present: 33
['ALLEGANY', 'BROOME', 'CAYUGA', 'CHEMUNG', 'CHENANGO', 'CLINTON', 'COLUMBIA', 'CORTLAND', 'DELAWARE', 'ESSEX', 'FRANKLIN', 'FULTON', 'GREENE', 'HAMILTON', 'HERKIMER', 'JEFFERSON', 'LEWIS', 'MADISON', 'MONTGOMERY', 'ONEIDA', 'ORANGE', 'OSWEGO', 'OTSEGO', 'SCHENECTADY', 'SCHOHARIE', 'SCHUYLER', 'ST LAWRENCE', 'SULLIVAN', 'TIOGA', 'TOMPKINS', 'ULSTER', 'WARREN', 'WASHINGTON']

In [3]:
#### NON-RURAL ENROLLMENT

import pandas as pd

# Paths
full_path = "/Users/emmamurphy/dataProjects/migranted/2023-24_ELL_Enrollment.csv"
filtered_path = "/Users/emmamurphy/dataProjects/migranted/Data/Cleaned data and Analysis/enrollment.csv"
out_path = "/Users/emmamurphy/dataProjects/migranted/Data/Cleaned data and Analysis/enrollment_not_in_enrollment.csv"

# Load
full = pd.read_csv(full_path, dtype=str)
filtered = pd.read_csv(filtered_path, dtype=str)

# Clean column names
full.columns = full.columns.str.strip()
filtered.columns = filtered.columns.str.strip()

# Pick best school key for exclusion
key_candidates = ["INSTITUTION_ID", "ENTITY_CD", "ENTITY_NAME"]
key = next((k for k in key_candidates if k in full.columns and k in filtered.columns), None)
if key is None:
    raise ValueError(f"No shared key found. Need one of: {key_candidates}")

full[key] = full[key].fillna("").astype(str).str.strip()
filtered[key] = filtered[key].fillna("").astype(str).str.strip()

# Exclude schools already in enrollment.csv
exclude_keys = set(filtered[key])
remaining = full[~full[key].isin(exclude_keys)].copy()

# Apply same column filter/order as enrollment.csv
cols_to_keep = [c for c in filtered.columns if c in remaining.columns]
remaining = remaining[cols_to_keep].copy()

# If enrollment.csv is non-zero ELL only, apply same rule
if "NUM_TOTAL_ELL" in remaining.columns and "NUM_TOTAL_ELL" in filtered.columns:
    f_num = pd.to_numeric(filtered["NUM_TOTAL_ELL"], errors="coerce")
    if (f_num.fillna(0) > 0).all():
        remaining["NUM_TOTAL_ELL"] = pd.to_numeric(remaining["NUM_TOTAL_ELL"], errors="coerce").fillna(0)
        remaining = remaining[remaining["NUM_TOTAL_ELL"] > 0].copy()

# If enrollment.csv is sorted by NUM_TOTAL_ELL desc, keep same behavior
if "NUM_TOTAL_ELL" in remaining.columns:
    remaining["NUM_TOTAL_ELL"] = pd.to_numeric(remaining["NUM_TOTAL_ELL"], errors="coerce").fillna(0)
    remaining = remaining.sort_values("NUM_TOTAL_ELL", ascending=False)

# Save
remaining.to_csv(out_path, index=False)

print("Key used:", key)
print("Rows in full:", len(full))
print("Rows excluded (already in enrollment.csv):", len(full) - len(remaining))
print("Rows saved:", len(remaining))
print("Saved to:", out_path)
remaining.head(20)

Key used: INSTITUTION_ID
Rows in full: 1050
Rows excluded (already in enrollment.csv): 283
Rows saved: 767
Saved to: /Users/emmamurphy/dataProjects/migranted/Data/Cleaned data and Analysis/enrollment_not_in_enrollment.csv

,ENTITY_NAME,PER_MALE,PER_FEMALE,PER_AM_IND,PER_BLACK,PER_HISP,PER_ASIAN,PER_WHITE,PER_MULTI,PER_KHALF,...,GRADE_11,GRADE_12,GRADE_UGS,0-3 YEARS,4-6 YEARS,7+ YEARS,SIFE,ENG_NEW_LANG,ONE_TWO_WAY_DUAL_LANG,TRAN_BILING_ED
149,NYC GEOG DIST #24 - QUEENS,53,47,0,0,88,8,3,0,0,...,628,318,32,12797,3218,2168,478,12802,2176,1703
123,NYC GEOG DIST #20 - BROOKLYN,56,44,0,1,32,47,19,1,0,...,392,338,44,8733,2263,1811,447,9432,477,1964
698,NYC GEOG DIST #30 - QUEENS,54,46,1,1,80,11,7,0,0,...,373,296,36,9166,1326,1170,642,7528,1330,1751
574,NYC GEOG DIST #10 - BRONX,54,46,1,3,91,3,2,0,0,...,547,358,17,6599,2283,2196,759,6894,393,2680
156,NYC GEOG DIST #25 - QUEENS,55,45,0,0,48,48,2,1,0,...,414,294,18,7594,1531,1120,257,7578,428,1567
124,NYC GEOG DIST #21 - BROOKLYN,56,44,1,1,25,27,45,1,0,...,459,269,12,6761,1384,1075,186,8049,227,142
910,BRENTWOOD UFSD,55,45,1,2,95,1,1,0,0,...,374,337,65,4515,1868,1353,670,2939,11,4742
454,NYC GEOG DIST # 2 - MANHATTAN,56,44,0,7,66,18,8,1,0,...,651,294,7,6501,706,972,1083,6618,149,544
803,EAST RAMAPO CSD (SPRING VALLEY),54,46,0,5,92,1,2,0,0,...,399,293,29,4898,1432,849,169,4563,0,2614
688,NYC GEOG DIST #28 - QUEENS,53,47,1,2,62,23,11,1,0,...,336,143,35,5744,1102,916,474,6363,277,488
556,NYC GEOG DIST # 9 - BRONX,53,47,1,8,89,1,1,0,0,...,384,221,14,4736,1551,1377,481,4513,1002,1288
158,NYC GEOG DIST #27 - QUEENS,55,45,1,2,74,19,3,0,0,...,274,194,12,5911,1074,835,307,6634,74,368
222,BUFFALO CITY SD,56,44,0,24,32,35,8,1,0,...,284,188,58,3352,1399,1521,133,5064,992,216
499,NYC GEOG DIST # 6 - MANHATTAN,54,46,0,2,95,1,2,1,0,...,317,232,33,4454,1097,1038,505,2632,1645,1766
449,NYC SPEC SCHOOLS - DIST 75,71,29,1,6,62,21,9,0,0,...,27,37,2621,0,0,0,0,0,0,0
128,NYC GEOG DIST #22 - BROOKLYN,55,45,1,7,18,28,45,2,0,...,156,127,6,5134,921,726,89,6053,149,17
704,NYC GEOG DIST #31 - STATEN ISLAND,56,44,0,1,50,27,22,1,0,...,279,161,13,3875,993,983,102,5006,502,74
588,NYC GEOG DIST #11 - BRONX,55,45,1,6,68,10,15,0,0,...,243,147,25,3683,1138,1104,183,5198,13,96
630,NYC GEOG DIST #15 - BROOKLYN,56,44,0,1,65,26,7,1,0,...,196,127,6,3320,926,931,185,3069,1548,105
601,NYC GEOG DIST #12 - BRONX,53,47,0,4,91,3,1,0,0,...,270,182,5,3141,1041,919,386,3808,144,585

In [7]:
#### CLEAN DATA

import pandas as pd

# Use the file that already includes COUNTY
source_path = "/Users/emmamurphy/dataProjects/migranted/Data/Original data and Cleaning/2023-24_ELL_Enrollment_with_county.csv"
df = pd.read_csv(source_path, dtype=str)
df.columns = df.columns.str.strip()

target_cols = [
    "ENTITY_NAME",
    "NUM_TOTAL_ELL",
    "NUM_HISP",
    "0-3 YEARS",
    "4-6 YEARS",
    "7+ YEARS",
    "SIFE",
    "ENG_NEW_LANG",
    "ONE_TWO_WAY_DUAL_LANG",
    "TRAN_BILING_ED",
    "COUNTY",
]

missing = [c for c in target_cols if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns in source file: {missing}")

same_cols_sorted_df = df[target_cols].copy()
same_cols_sorted_df["NUM_TOTAL_ELL"] = pd.to_numeric(same_cols_sorted_df["NUM_TOTAL_ELL"], errors="coerce").fillna(0)

same_cols_sorted_df = (
    same_cols_sorted_df[same_cols_sorted_df["NUM_TOTAL_ELL"] > 0]
    .sort_values("NUM_TOTAL_ELL", ascending=False)
    .reset_index(drop=True)
)

print("Rows:", len(same_cols_sorted_df))
same_cols_sorted_df.head(20)

Rows: 943

,ENTITY_NAME,NUM_TOTAL_ELL,NUM_HISP,0-3 YEARS,4-6 YEARS,7+ YEARS,SIFE,ENG_NEW_LANG,ONE_TWO_WAY_DUAL_LANG,TRAN_BILING_ED,COUNTY
0,NYC GEOG DIST #24 - QUEENS,13945,12208,12797,3218,2168,478,12802,2176,1703,QUEENS
1,NYC GEOG DIST #20 - BROOKLYN,9970,3160,8733,2263,1811,447,9432,477,1964,KINGS
2,NYC GEOG DIST #30 - QUEENS,8515,6848,9166,1326,1170,642,7528,1330,1751,QUEENS
3,NYC GEOG DIST #10 - BRONX,8205,7506,6599,2283,2196,759,6894,393,2680,BRONX
4,NYC GEOG DIST #25 - QUEENS,7688,3701,7594,1531,1120,257,7578,428,1567,QUEENS
5,NYC GEOG DIST #21 - BROOKLYN,7074,1800,6761,1384,1075,186,8049,227,142,KINGS
6,BRENTWOOD UFSD,6604,6242,4515,1868,1353,670,2939,11,4742,SUFFOLK
7,NYC GEOG DIST # 2 - MANHATTAN,5774,3808,6501,706,972,1083,6618,149,544,NEW YORK
8,EAST RAMAPO CSD (SPRING VALLEY),5707,5247,4898,1432,849,169,4563,0,2614,ROCKLAND
9,NYC GEOG DIST #28 - QUEENS,5461,3399,5744,1102,916,474,6363,277,488,QUEENS
10,NYC GEOG DIST # 9 - BRONX,5458,4867,4736,1551,1377,481,4513,1002,1288,BRONX
11,NYC GEOG DIST #27 - QUEENS,5385,4011,5911,1074,835,307,6634,74,368,QUEENS
12,BUFFALO CITY SD,5133,1625,3352,1399,1521,133,5064,992,216,ERIE
13,NYC GEOG DIST # 6 - MANHATTAN,4694,4445,4454,1097,1038,505,2632,1645,1766,NEW YORK
14,NYC SPEC SCHOOLS - DIST 75,4621,2886,0,0,0,0,0,0,0,KINGS
15,NYC GEOG DIST #22 - BROOKLYN,4605,808,5134,921,726,89,6053,149,17,KINGS
16,NYC GEOG DIST #31 - STATEN ISLAND,4576,2269,3875,993,983,102,5006,502,74,RICHMOND
17,NYC GEOG DIST #11 - BRONX,4249,2869,3683,1138,1104,183,5198,13,96,BRONX
18,NYC GEOG DIST #15 - BROOKLYN,3812,2469,3320,926,931,185,3069,1548,105,KINGS
19,NYC GEOG DIST #12 - BRONX,3532,3218,3141,1041,919,386,3808,144,585,BRONX

In [8]:
#### SAVE CSV

# Save the current dataframe as requested
out_path = "/Users/emmamurphy/dataProjects/migranted/Data/Cleaned data and Analysis/enrollment_nonrural_cleaned.csv"
same_cols_sorted_df.to_csv(out_path, index=False)

print("Saved:", out_path)

Saved: /Users/emmamurphy/dataProjects/migranted/Data/Cleaned data and Analysis/enrollment_nonrural_cleaned.csv